- hosts: localhost
  tasks:

  - name: Copying files for testing
    copy: 
      src: /etc/passwd
      dest: /tmp/


  - name: Installing Pkg for apache server
    yum:
      name: httpd
      state: present

  - name: Starting services for apache server
    service:
       name: httpd
       state: started
       
